In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import preprocessing, linear_model
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import ShuffleSplit
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

In [2]:
def train_test_spliter(df, random_seed=0, test_size=0.20, n_splits=1):
    trainm = preprocessing.maxabs_scale(df, axis=0, copy=True)
    col = df.columns
    df1 = pd.DataFrame(data=trainm, columns=col)
    rs = ShuffleSplit(n_splits=n_splits, test_size=test_size, random_state=random_seed)
    for train_index, test_index in rs.split(df):
        pass
    traindf = pd.DataFrame(data=df, index=train_index)
    testdf = pd.DataFrame(data=df, index=test_index)
    return traindf, testdf

In [3]:
train_test_spliter(pd.read_csv('../data/test1.csv'))[0].head(10)

a         b         c        y1        y2
134  0.589902  0.671126  0.341183  0.430241  1.769707
66   0.011837  0.431590  0.719130  0.318881  0.035511
26   0.777405  0.717705  0.831068  1.242539  2.332215
113  0.214004  0.231163  0.603016  0.268443  0.642012
168  0.430676  0.386141  0.512394  0.418532  1.292028
63   0.748453  0.732463  0.142701  0.211328  2.245359
8    0.675500  0.575396  0.656886  0.821696  2.026501
75   0.763285  0.185831  0.873224  0.828790  2.289856
118  0.865976  0.575599  0.964822  1.390863  2.597927
143  0.467573  0.692257  0.695690  0.806882  1.402720

In [4]:
train_test_spliter(pd.read_csv('../data/test1.csv'))[1].head(10)

a         b         c        y1        y2
18   0.203861  0.378814  0.177686  0.103533  0.611584
170  0.688840  0.531851  0.754094  0.920515  2.066519
107  0.360372  0.487634  0.843383  0.715193  1.081115
98   0.805632  0.254294  0.292346  0.309865  2.416895
177  0.569208  0.410178  0.269691  0.264131  1.707625
182  0.541083  0.854148  0.653009  0.911098  1.623250
5    0.584544  0.144620  0.433638  0.316193  1.753633
146  0.554896  0.725991  0.449658  0.575961  1.664688
12   0.485312  0.846474  0.864118  1.150820  1.455935
152  0.243379  0.324236  0.796994  0.452387  0.730138

In [5]:
df = pd.read_csv('../data/test1.csv')
col = df.columns
trainm = preprocessing.maxabs_scale(df, axis=0, copy=True)
df1 = pd.DataFrame(data=trainm, columns=col)
df1.head(3)

a         b         c        y1        y2
0  0.622063  0.147337  0.321680  0.166659  0.622063
1  0.089455  0.423165  0.867130  0.298726  0.089455
2  0.209278  0.491120  0.347587  0.163670  0.209278

In [6]:
rs = ShuffleSplit(n_splits=1, test_size=.20, random_state=0)
rs.get_n_splits(df)

1

In [7]:
for train_index, test_index in rs.split(df):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [134  66  26 113 168  63   8  75 118 143  71 124 184  97 149  24  30 160
  40  56 131  96 181  19 153  92  54 163  51  86 139  90 137 101 144  89
 109  14  27 141 187  46 138 195 108  62   2  59 136 197  43  10 194  73
 196 178 175 126  93 112 158 191  50   0  94 110  95  64 167  41  69  49
  48  85  13 161  23 186 135  20  15  78 104  52 100  76   3 116 164 198
   6  68  84 121 155 171 156  91 199  11 119 102  35  57  65   1 120 162
  42 105 132 173  17  38 133  53 157 128  34  28 114 151  31 166 127 176
  32 142 169 147  29  99  82  79 115 148 193  72  77  25 165  81 188 174
 190  39  58 140  88  70  87  36  21   9 103  67 192 117  47 172] TEST: [ 18 170 107  98 177 182   5 146  12 152  61 125 180 154  80   7  33 130
  37  74 183 145  45 159  60 123 179 185 122  44  16  55 150 111  22 189
 129   4  83 106]


In [8]:
traindf = pd.DataFrame(data=df, index=train_index)
traindf.head(3)

a         b         c        y1        y2
134  0.589902  0.671126  0.341183  0.430241  1.769707
66   0.011837  0.431590  0.719130  0.318881  0.035511
26   0.777405  0.717705  0.831068  1.242539  2.332215

In [9]:
testdf = pd.DataFrame(data=df, index=test_index)
testdf.head(3)

a         b         c        y1        y2
18   0.203861  0.378814  0.177686  0.103533  0.611584
170  0.688840  0.531851  0.754094  0.920515  2.066519
107  0.360372  0.487634  0.843383  0.715193  1.081115

In [10]:
# testdf_scaled = preprocessing.scale(testdf)
# traindf_scaled = preprocessing.scale(traindf)
len(traindf) == 160 and len(testdf) == 40

True

In [11]:
X_train = pd.DataFrame(data=traindf, columns=['a', 'b', 'c'])
Y_train = pd.DataFrame(data=traindf, columns=['y1', 'y2'])
X_test = pd.DataFrame(data=testdf, columns=['a', 'b', 'c'])
Y_test = pd.DataFrame(data=testdf, columns=['y1', 'y2'])

In [12]:
reg = linear_model.LinearRegression()
reg.fit(X_train, Y_train)
linear_result = reg.predict(X_test)
linear_result

array([[-0.0133893 ,  0.61158362],
       [ 0.85303623,  2.06651889],
       [ 0.76722845,  1.0811146 ],
       [ 0.33376524,  2.41689458],
       [ 0.26446273,  1.70762508],
       [ 0.8177701 ,  1.62325012],
       [ 0.32307462,  1.75363313],
       [ 0.56874786,  1.66468756],
       [ 0.99760833,  1.45593516],
       [ 0.59713324,  0.73013849],
       [-0.07974384,  0.29097057],
       [ 0.56781565,  1.50061887],
       [ 0.11509854,  0.70961314],
       [ 0.46329389,  1.13702771],
       [ 0.82590833,  1.54034219],
       [ 0.55068725,  0.59054972],
       [ 0.7121467 ,  2.2373307 ],
       [ 0.63140541,  2.6451551 ],
       [ 0.76103129,  1.98468749],
       [ 0.96287789,  1.54317128],
       [ 0.60666496,  2.64302044],
       [ 0.98684464,  2.25285545],
       [ 0.35209884,  1.7666799 ],
       [ 0.26677717,  1.54724406],
       [ 1.18743731,  2.28576559],
       [ 0.5303727 ,  2.96419331],
       [ 0.61814839,  1.89198992],
       [ 0.3708044 ,  0.05789819],
       [ 1.03196633,

In [13]:
reg = linear_model.LinearRegression()
reg.fit(X_train, Y_train)
linear_result = reg.predict(X_test)
linear_result

array([[-0.0133893 ,  0.61158362],
       [ 0.85303623,  2.06651889],
       [ 0.76722845,  1.0811146 ],
       [ 0.33376524,  2.41689458],
       [ 0.26446273,  1.70762508],
       [ 0.8177701 ,  1.62325012],
       [ 0.32307462,  1.75363313],
       [ 0.56874786,  1.66468756],
       [ 0.99760833,  1.45593516],
       [ 0.59713324,  0.73013849],
       [-0.07974384,  0.29097057],
       [ 0.56781565,  1.50061887],
       [ 0.11509854,  0.70961314],
       [ 0.46329389,  1.13702771],
       [ 0.82590833,  1.54034219],
       [ 0.55068725,  0.59054972],
       [ 0.7121467 ,  2.2373307 ],
       [ 0.63140541,  2.6451551 ],
       [ 0.76103129,  1.98468749],
       [ 0.96287789,  1.54317128],
       [ 0.60666496,  2.64302044],
       [ 0.98684464,  2.25285545],
       [ 0.35209884,  1.7666799 ],
       [ 0.26677717,  1.54724406],
       [ 1.18743731,  2.28576559],
       [ 0.5303727 ,  2.96419331],
       [ 0.61814839,  1.89198992],
       [ 0.3708044 ,  0.05789819],
       [ 1.03196633,

In [14]:
max_depth = 30

# Random forest with multioutput regressor
regr_multirf = MultiOutputRegressor(RandomForestRegressor(max_depth=max_depth,
                                                          random_state=0))
regr_multirf.fit(X_train, Y_train)
mo_rf_result = regr_multirf.predict(X_test)
mo_rf_result

array([[ 0.15504522,  0.62410882],
       [ 0.94258987,  2.06367173],
       [ 0.60684557,  1.07100332],
       [ 0.39044133,  2.4260313 ],
       [ 0.26756044,  1.70165808],
       [ 0.8316347 ,  1.64419902],
       [ 0.34639838,  1.80217102],
       [ 0.46958867,  1.66954325],
       [ 0.95797209,  1.45505909],
       [ 0.44284326,  0.71746858],
       [ 0.10719925,  0.27196706],
       [ 0.51325019,  1.47584156],
       [ 0.10350421,  0.73169125],
       [ 0.37365638,  1.12511466],
       [ 0.71637365,  1.54106582],
       [ 0.48706203,  0.60291723],
       [ 0.73645621,  2.23524549],
       [ 0.51579036,  2.63620654],
       [ 0.75848587,  1.99774033],
       [ 0.70863927,  1.54106582],
       [ 0.7396866 ,  2.60792322],
       [ 0.90153424,  2.25442006],
       [ 0.38808809,  1.79389409],
       [ 0.3456077 ,  1.54205025],
       [ 1.30189605,  2.28128426],
       [ 0.5460828 ,  2.95551202],
       [ 0.52634321,  1.87896363],
       [ 0.3833613 ,  0.04236043],
       [ 1.02211503,

In [15]:
# Just random forest
regr_rf = RandomForestRegressor(max_depth=max_depth, random_state=2)
regr_rf.fit(X_train, Y_train)
y_rf = regr_rf.predict(X_test)
y_rf

array([[ 0.06127   ,  0.60452084],
       [ 0.97547184,  2.03199233],
       [ 0.63641424,  1.17509859],
       [ 0.38828105,  2.48104126],
       [ 0.33284398,  1.70126009],
       [ 0.91795154,  1.66935698],
       [ 0.39633759,  1.74103495],
       [ 0.35503419,  1.71304948],
       [ 0.92455664,  1.25917362],
       [ 0.51459831,  0.64117552],
       [ 0.1712191 ,  0.25581403],
       [ 0.63589766,  1.46101492],
       [ 0.30166641,  0.66015797],
       [ 0.45184733,  1.07632865],
       [ 0.71161682,  1.46375987],
       [ 0.43519672,  0.59454226],
       [ 0.87419861,  2.104836  ],
       [ 0.48518591,  2.65203283],
       [ 0.84660367,  1.92226387],
       [ 0.72810625,  1.43110344],
       [ 0.76633891,  2.61073379],
       [ 1.04233641,  2.21280254],
       [ 0.41323589,  1.71716306],
       [ 0.46607276,  1.44143655],
       [ 1.21239056,  2.27170825],
       [ 0.5929057 ,  2.88596593],
       [ 0.65412505,  1.95855544],
       [ 0.34882872,  0.0666409 ],
       [ 0.92890863,

In [16]:
mean_squared_error(Y_test, linear_result)

0.0067207014475528125

In [17]:
mean_squared_error(Y_test, mo_rf_result)

0.0072324949232488497

In [18]:
mean_squared_error(Y_test, y_rf)

0.013725086045229326

In [19]:
y1 = [1, 0.7]
y2 = [1.2, 1]
mean_squared_error(y1, y2)

0.065000000000000002

In [20]:
y1 = [1]
y2 = [1.2]
mean_squared_error(y1, y2)

0.03999999999999998

In [21]:
y1 = [0.7]
y2 = [1]
mean_squared_error(y1, y2)

0.090000000000000024