In [1]:
import pandas as pd
import seaborn as sns
import numpy as np


from sklearn import linear_model, svm, tree
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import ShuffleSplit
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
df = pd.read_csv('ready.csv')
df = df.fillna(0)

In [2]:
df.columns
df = df[['Canadian Citizen', 'No Response(Citizen)', 'Non-Canadian Citizen',
       'Refugee', 'No Longer In Use', 'Occupied', 'Unoccupied',
       'Employed 0-30 Hours', 'Employed 30+ Hours', 'Gr.10 - Gr.12',
       'Gr.7 - Gr.9', 'Homemaker', 'Kindergarten - Gr.6',
       'No Response(Employment)', 'Permanently Unable to Work',
       'Post Secondary Student', 'Preschool', 'Retired', 'Unemployed',
       'Common Law', 'Married', 'Never Married', 'No Response(Marital)',
       'Separated/Divorced', 'Widowed', 'Bicycle',
       'Car/Truck/Van (as Driver)', 'Car/Truck/Van (as Passenger)',
       'No Response(Transportation)', 'Other', 'Public Transit', 'Walk',
       'Catholic', 'No Response(School)', 'Public', 'Assault', 'Break and Enter', 'Homicide',
       'Robbery', 'Sexual Assaults', 'Theft From Vehicle', 'Theft Of Vehicle',
       'Theft Over $5000']]

In [3]:
def train_test_spliter(df, random_seed=0, test_size=0.20, n_splits=1):
    # trainm = preprocessing.maxabs_scale(df, axis=0, copy=True)
    col = df.columns
    df1 = pd.DataFrame(data=df, columns=col)
    rs = ShuffleSplit(n_splits=n_splits, test_size=test_size, random_state=random_seed)
    for train_index, test_index in rs.split(df):
        pass
    traindf = pd.DataFrame(data=df, index=train_index)
    testdf = pd.DataFrame(data=df, index=test_index)
    return traindf, testdf


traindf, testdf = train_test_spliter(df)

X_train = pd.DataFrame(data=traindf, columns=['Canadian Citizen', 'No Response(Citizen)', 'Non-Canadian Citizen',
       'Refugee', 'No Longer In Use', 'Occupied', 'Unoccupied',
       'Employed 0-30 Hours', 'Employed 30+ Hours', 'Gr.10 - Gr.12',
       'Gr.7 - Gr.9', 'Homemaker', 'Kindergarten - Gr.6',
       'No Response(Employment)', 'Permanently Unable to Work',
       'Post Secondary Student', 'Preschool', 'Retired', 'Unemployed',
       'Common Law', 'Married', 'Never Married', 'No Response(Marital)',
       'Separated/Divorced', 'Widowed', 'Bicycle',
       'Car/Truck/Van (as Driver)', 'Car/Truck/Van (as Passenger)',
       'No Response(Transportation)', 'Other', 'Public Transit', 'Walk',
       'Catholic', 'No Response(School)', 'Public'])
# X_train = preprocessing.maxabs_scale(X_train, axis=0, copy=True)

Y_train = pd.DataFrame(data=traindf, columns=['Assault', 'Break and Enter', 'Homicide',
       'Robbery', 'Sexual Assaults', 'Theft From Vehicle', 'Theft Of Vehicle',
       'Theft Over $5000'])
X_test = pd.DataFrame(data=testdf, columns=['Canadian Citizen', 'No Response(Citizen)', 'Non-Canadian Citizen',
       'Refugee', 'No Longer In Use', 'Occupied', 'Unoccupied',
       'Employed 0-30 Hours', 'Employed 30+ Hours', 'Gr.10 - Gr.12',
       'Gr.7 - Gr.9', 'Homemaker', 'Kindergarten - Gr.6',
       'No Response(Employment)', 'Permanently Unable to Work',
       'Post Secondary Student', 'Preschool', 'Retired', 'Unemployed',
       'Common Law', 'Married', 'Never Married', 'No Response(Marital)',
       'Separated/Divorced', 'Widowed', 'Bicycle',
       'Car/Truck/Van (as Driver)', 'Car/Truck/Van (as Passenger)',
       'No Response(Transportation)', 'Other', 'Public Transit', 'Walk',
       'Catholic', 'No Response(School)', 'Public'])
X_test = preprocessing.maxabs_scale(X_test, axis=0, copy=True)

Y_test = pd.DataFrame(data=testdf, columns=['Assault', 'Break and Enter', 'Homicide',
       'Robbery', 'Sexual Assaults', 'Theft From Vehicle', 'Theft Of Vehicle',
       'Theft Over $5000'])

In [4]:
from sklearn import preprocessing
import numpy as np
import pandas as pd

In [5]:
X_scaled = preprocessing.scale(X_train)
Y_scaled = preprocessing.scale(Y_train)

In [6]:
X_scaled.mean(axis=0)

array([  2.70315171e-17,   1.02977208e-17,  -4.15126870e-17,
         5.14886040e-18,  -7.07968306e-18,  -2.18826567e-17,
        -1.73774039e-17,  -5.08449965e-17,  -7.01532230e-17,
         3.82946493e-17,  -2.25262643e-17,  -5.72810720e-17,
         7.72329061e-18,  -3.21803775e-18,   9.01050571e-18,
        -3.08931624e-17,   6.62915777e-17,   2.38134794e-17,
        -6.69351853e-17,  -7.20840457e-17,   2.70315171e-17,
        -4.79487625e-17,  -2.96059473e-17,  -1.09413284e-17,
         4.63397436e-17,   3.57202191e-17,  -1.09413284e-17,
         6.43607551e-19,  -1.71360510e-17,  -5.08449965e-17,
         2.25262643e-18,   1.35157586e-17,  -1.25503472e-17,
        -6.62915777e-17,  -4.15126870e-17])

In [7]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
from sklearn.cross_decomposition import CCA
n_components=8
cca = CCA(n_components)
cca.fit(X_scaled,Y_scaled)
X_c, Y_c = cca.transform(X_scaled, Y_scaled)

c = []
for i in range(n_components):
    c.append(np.corrcoef(X_c[:,i], Y_c[:,i])[0,1])

print(c)
    
T = np.empty(shape=(n_components,n_components))
for i in range(n_components):
     T[i] = Y_c.T[:,i]
        
print(T)

[0.80711606642881806, 0.38367750028102771, 0.20481374137809025, 0.17980884030270702, 0.11183053453952706, 0.08349010891479397, 0.068004477844928413, 0.055149965259994341]
[[  8.03315836e-01  -3.45466728e-01   5.74411120e-03  -2.87913653e-02
    1.01554073e-02   1.12876404e-01   1.40490039e-02  -9.53095452e-02]
 [ -1.73749430e+00  -1.36842368e+00   7.59291667e-01   4.98095465e-01
   -4.11653487e-01  -7.32137203e-01  -4.70623068e-01   2.68827458e+00]
 [  8.03315836e-01  -3.45466728e-01   5.74411120e-03  -2.87913653e-02
    1.01554073e-02   1.12876404e-01   1.40490039e-02  -9.53095452e-02]
 [  8.03315836e-01  -3.45466728e-01   5.74411120e-03  -2.87913653e-02
    1.01554073e-02   1.12876404e-01   1.40490039e-02  -9.53095452e-02]
 [ -6.09992366e+00   4.36213062e+00  -4.10465188e+00   7.53227135e+00
   -5.96469368e+00   9.38717931e-01   1.33201068e+00  -3.64881547e+00]
 [ -1.31141048e+00   9.82915966e-01  -1.54037595e+00   8.17854952e-01
    4.59531947e-01   8.60899045e-01   4.24580319e-01  

In [9]:
from sklearn import linear_model

In [10]:
regr = linear_model.LinearRegression()
Y_star = Y_scaled * np.asmatrix(T)
Y_hat = np.empty(shape=(len(X_scaled),8))

for x in range(8):
    regr.fit(X_scaled, Y_star[:,x])
    Y_hat[:, x] = np.ndarray.flatten(regr.predict(X_scaled))

In [11]:
Y_hat

array([[ 2.22941451, -0.65375442,  1.23066356, ..., -0.38554792,
        -0.36882072, -0.31033854],
       [-4.31648393,  1.44316941, -2.51079152, ...,  0.72596331,
         0.78517098, -0.21463541],
       [ 2.22941451, -0.65375442,  1.23066356, ..., -0.38554792,
        -0.36882072, -0.31033854],
       ..., 
       [ 2.1879106 , -0.64984817,  1.2230952 , ..., -0.38652448,
        -0.36772208, -0.28934244],
       [ 0.94718794, -0.31262893,  0.74265697, ..., -0.26039533,
        -0.20953422, -0.117559  ],
       [ 2.22941451, -0.65375442,  1.23066356, ..., -0.38554792,
        -0.36882072, -0.31033854]])

In [12]:
r = len(X_scaled.T)/len(X_scaled)
dx=[]
for i in range(len(c)):
    dxi=((1-r)*(c[i]**2-r))/((1-r)**2)*c[i]**2+(r**2)*(1-c[i]**2)
    if dxi<0:
        dx.append(0)
    else:
        dx.append(dxi)
dx

[0.42400968140030704,
 0.021473150930706092,
 0.0016982915858584817,
 0.00099806773154172113,
 0.00013927591722924176,
 4.0094602034454847e-05,
 1.6579713916332103e-05,
 6.9416626713172407e-06]

In [13]:
dx = np.asmatrix(dx)
Y_new = np.multiply(Y_hat, dx)
Y_new

matrix([[  9.45293335e-01,  -1.40381673e-02,   2.09002556e-03, ...,
          -1.54583904e-05,  -6.11494196e-06,  -2.15426543e-06],
        [ -1.83023098e+00,   3.09893946e-02,  -4.26405611e-03, ...,
           2.91072101e-05,   1.30179103e-05,  -1.48992662e-06],
        [  9.45293335e-01,  -1.40381673e-02,   2.09002556e-03, ...,
          -1.54583904e-05,  -6.11494196e-06,  -2.15426543e-06],
        ..., 
        [  9.27695277e-01,  -1.39542878e-02,   2.07717228e-03, ...,
          -1.54975453e-05,  -6.09672694e-06,  -2.00851763e-06],
        [  4.01616859e-01,  -6.71312817e-03,   1.26124808e-03, ...,
          -1.04404472e-05,  -3.47401737e-06,  -8.16054890e-07],
        [  9.45293335e-01,  -1.40381673e-02,   2.09002556e-03, ...,
          -1.54583904e-05,  -6.11494196e-06,  -2.15426543e-06]])

In [14]:
result=(Y_new * np.linalg.inv(np.asmatrix(T)))

In [15]:
result

matrix([[  9.12728906e+14,  -1.72504214e-01,  -2.10274229e+15, ...,
          -1.19077385e-01,  -2.24569655e-01,  -9.93702906e-02],
        [ -1.75916222e+15,   3.32761901e-01,   4.05864146e+15, ...,
           2.30042261e-01,   4.33102620e-01,   1.95086275e-01],
        [  9.12728906e+14,  -1.72504214e-01,  -2.10274229e+15, ...,
          -1.19077385e-01,  -2.24569655e-01,  -9.93702906e-02],
        ..., 
        [  8.95404909e+14,  -1.69238871e-01,  -2.06309984e+15, ...,
          -1.16838660e-01,  -2.20289372e-01,  -9.76197167e-02],
        [  3.88774256e+14,  -7.31271780e-02,  -8.92731740e+14, ...,
          -5.06049339e-02,  -9.47143090e-02,  -4.23828437e-02],
        [  9.12728906e+14,  -1.72504214e-01,  -2.10274229e+15, ...,
          -1.19077385e-01,  -2.24569655e-01,  -9.93702906e-02]])

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
mean_squared_error(Y_scaled, result)

2.2953781856079804e+30

In [18]:
mean_squared_error(Y_train, result)

2.2953781856079809e+30

In [19]:
crimes = ['Assault', 'Break and Enter', 'Homicide', 'Robbery', 'Sexual Assaults',
       'Theft From Vehicle', 'Theft Of Vehicle', 'Theft Over $5000']

In [20]:
result1 = []
for i in range(len(crimes)):
    result1.append([np.sqrt(mean_squared_error(Y_train[crimes[i]], result[:,i])), crimes[i], 'Linear Regression'])
    
result1

[[1510338621318495.0, 'Assault', 'Linear Regression'],
 [1.8067644105870351, 'Break and Enter', 'Linear Regression'],
 [3488399634215690.5, 'Homicide', 'Linear Regression'],
 [1978123031011947.2, 'Robbery', 'Linear Regression'],
 [0.49693393076651105, 'Sexual Assaults', 'Linear Regression'],
 [2.8372757248429941, 'Theft From Vehicle', 'Linear Regression'],
 [1.4609922366816115, 'Theft Of Vehicle', 'Linear Regression'],
 [0.33590054444014728, 'Theft Over $5000', 'Linear Regression']]