In [1]:
import pandas as pd
import seaborn as sns
import numpy as np


from sklearn import linear_model, svm, tree
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import ShuffleSplit
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
df = pd.read_csv('ready.csv')
df = df.fillna(0)

In [2]:
df.columns
df = df[['Canadian Citizen', 'No Response(Citizen)', 'Non-Canadian Citizen',
       'Refugee', 'No Longer In Use', 'Occupied', 'Unoccupied',
       'Employed 0-30 Hours', 'Employed 30+ Hours', 'Gr.10 - Gr.12',
       'Gr.7 - Gr.9', 'Homemaker', 'Kindergarten - Gr.6',
       'No Response(Employment)', 'Permanently Unable to Work',
       'Post Secondary Student', 'Preschool', 'Retired', 'Unemployed',
       'Common Law', 'Married', 'Never Married', 'No Response(Marital)',
       'Separated/Divorced', 'Widowed', 'Bicycle',
       'Car/Truck/Van (as Driver)', 'Car/Truck/Van (as Passenger)',
       'No Response(Transportation)', 'Other', 'Public Transit', 'Walk',
       'Catholic', 'No Response(School)', 'Public', 'Assault', 'Break and Enter', 'Homicide',
       'Robbery', 'Sexual Assaults', 'Theft From Vehicle', 'Theft Of Vehicle',
       'Theft Over $5000']]

In [3]:
def train_test_spliter(df, random_seed=0, test_size=0.20, n_splits=1):
    # trainm = preprocessing.maxabs_scale(df, axis=0, copy=True)
    col = df.columns
    df1 = pd.DataFrame(data=df, columns=col)
    rs = ShuffleSplit(n_splits=n_splits, test_size=test_size, random_state=random_seed)
    for train_index, test_index in rs.split(df):
        pass
    traindf = pd.DataFrame(data=df, index=train_index)
    testdf = pd.DataFrame(data=df, index=test_index)
    return traindf, testdf


traindf, testdf = train_test_spliter(df)

X_train = pd.DataFrame(data=traindf, columns=['Canadian Citizen', 'No Response(Citizen)', 'Non-Canadian Citizen',
       'Refugee', 'No Longer In Use', 'Occupied', 'Unoccupied',
       'Employed 0-30 Hours', 'Employed 30+ Hours', 'Gr.10 - Gr.12',
       'Gr.7 - Gr.9', 'Homemaker', 'Kindergarten - Gr.6',
       'No Response(Employment)', 'Permanently Unable to Work',
       'Post Secondary Student', 'Preschool', 'Retired', 'Unemployed',
       'Common Law', 'Married', 'Never Married', 'No Response(Marital)',
       'Separated/Divorced', 'Widowed', 'Bicycle',
       'Car/Truck/Van (as Driver)', 'Car/Truck/Van (as Passenger)',
       'No Response(Transportation)', 'Other', 'Public Transit', 'Walk',
       'Catholic', 'No Response(School)', 'Public'])
# X_train = preprocessing.maxabs_scale(X_train, axis=0, copy=True)

Y_train = pd.DataFrame(data=traindf, columns=['Assault', 'Break and Enter', 'Homicide',
       'Robbery', 'Sexual Assaults', 'Theft From Vehicle', 'Theft Of Vehicle',
       'Theft Over $5000'])
X_test = pd.DataFrame(data=testdf, columns=['Canadian Citizen', 'No Response(Citizen)', 'Non-Canadian Citizen',
       'Refugee', 'No Longer In Use', 'Occupied', 'Unoccupied',
       'Employed 0-30 Hours', 'Employed 30+ Hours', 'Gr.10 - Gr.12',
       'Gr.7 - Gr.9', 'Homemaker', 'Kindergarten - Gr.6',
       'No Response(Employment)', 'Permanently Unable to Work',
       'Post Secondary Student', 'Preschool', 'Retired', 'Unemployed',
       'Common Law', 'Married', 'Never Married', 'No Response(Marital)',
       'Separated/Divorced', 'Widowed', 'Bicycle',
       'Car/Truck/Van (as Driver)', 'Car/Truck/Van (as Passenger)',
       'No Response(Transportation)', 'Other', 'Public Transit', 'Walk',
       'Catholic', 'No Response(School)', 'Public'])
X_test = preprocessing.maxabs_scale(X_test, axis=0, copy=True)

Y_test = pd.DataFrame(data=testdf, columns=['Assault', 'Break and Enter', 'Homicide',
       'Robbery', 'Sexual Assaults', 'Theft From Vehicle', 'Theft Of Vehicle',
       'Theft Over $5000'])

In [4]:
from sklearn import preprocessing
import numpy as np
import pandas as pd

In [5]:
X_scaled = preprocessing.scale(X_train)
Y_scaled = preprocessing.scale(Y_train)

In [6]:
X_scaled.mean(axis=0)

array([  2.70315171e-17,   1.02977208e-17,  -4.15126870e-17,
         5.14886040e-18,  -7.07968306e-18,  -2.18826567e-17,
        -1.73774039e-17,  -5.08449965e-17,  -7.01532230e-17,
         3.82946493e-17,  -2.25262643e-17,  -5.72810720e-17,
         7.72329061e-18,  -3.21803775e-18,   9.01050571e-18,
        -3.08931624e-17,   6.62915777e-17,   2.38134794e-17,
        -6.69351853e-17,  -7.20840457e-17,   2.70315171e-17,
        -4.79487625e-17,  -2.96059473e-17,  -1.09413284e-17,
         4.63397436e-17,   3.57202191e-17,  -1.09413284e-17,
         6.43607551e-19,  -1.71360510e-17,  -5.08449965e-17,
         2.25262643e-18,   1.35157586e-17,  -1.25503472e-17,
        -6.62915777e-17,  -4.15126870e-17])

In [7]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
from sklearn.cross_decomposition import CCA
n_components=8
cca = CCA(n_components)
cca.fit(X_scaled,Y_scaled)
X_c, Y_c = cca.transform(X_scaled, Y_scaled)

c = []
for i in range(n_components):
    c.append(np.corrcoef(X_c[:,i], Y_c[:,i])[0,1])

print(c)
    
T = np.empty(shape=(n_components,n_components))
for i in range(n_components):
     T[i] = Y_c.T[:,i]
        
print(T)

[0.80711606642881872, 0.38367750028102765, 0.20481374137809011, 0.17980884030270711, 0.11183053453952699, 0.083490108914793873, 0.068004477844928482, 0.055149965259994285]
[[  8.03315836e-01  -3.45466728e-01   5.74411120e-03  -2.87913653e-02
    1.01554073e-02   1.12876404e-01   1.40490039e-02  -9.53095452e-02]
 [ -1.73749430e+00  -1.36842368e+00   7.59291667e-01   4.98095465e-01
   -4.11653487e-01  -7.32137203e-01  -4.70623068e-01   2.68827458e+00]
 [  8.03315836e-01  -3.45466728e-01   5.74411120e-03  -2.87913653e-02
    1.01554073e-02   1.12876404e-01   1.40490039e-02  -9.53095452e-02]
 [  8.03315836e-01  -3.45466728e-01   5.74411120e-03  -2.87913653e-02
    1.01554073e-02   1.12876404e-01   1.40490039e-02  -9.53095452e-02]
 [ -6.09992366e+00   4.36213062e+00  -4.10465188e+00   7.53227135e+00
   -5.96469368e+00   9.38717931e-01   1.33201068e+00  -3.64881547e+00]
 [ -1.31141048e+00   9.82915966e-01  -1.54037595e+00   8.17854952e-01
    4.59531947e-01   8.60899045e-01   4.24580319e-01 

In [9]:
from sklearn import linear_model

In [10]:
regr = linear_model.LinearRegression()
Y_star = Y_scaled * np.asmatrix(T)
Y_hat = np.empty(shape=(len(X_scaled),8))

for x in range(8):
    regr.fit(X_scaled, Y_star[:,x])
    Y_hat[:, x] = np.ndarray.flatten(regr.predict(X_scaled))

In [11]:
Y_hat

array([[ 2.24722641, -0.66645362,  1.24311777, ..., -0.39087386,
        -0.37319429, -0.30275839],
       [-4.35486524,  1.46708455, -2.5341328 , ...,  0.7311101 ,
         0.79265491, -0.2313942 ],
       [ 2.24722641, -0.66645362,  1.24311777, ..., -0.39087386,
        -0.37319429, -0.30275839],
       ..., 
       [ 2.20462387, -0.66327979,  1.23432871, ..., -0.39148421,
        -0.37215669, -0.28249471],
       [ 0.94903032, -0.31677041,  0.74523217, ..., -0.26160823,
        -0.21059663, -0.11364693],
       [ 2.24722641, -0.66645362,  1.24311777, ..., -0.39087386,
        -0.37319429, -0.30275839]])

In [12]:
r = len(X_scaled.T)/len(X_scaled)
dx=[]
for i in range(len(c)):
    dxi=((1-r)*(c[i]**2-r))/((1-r)**2)*c[i]**2+(r**2)*(1-c[i]**2)
    if dxi<0:
        dx.append(0)
    else:
        dx.append(dxi)
dx

[0.42400968140030848,
 0.021473150930706082,
 0.0016982915858584772,
 0.00099806773154172287,
 0.00013927591722924141,
 4.0094602034454643e-05,
 1.6579713916332177e-05,
 6.9416626713172136e-06]

In [13]:
dx = np.asmatrix(dx)
Y_new = np.multiply(Y_hat, dx)
Y_new

matrix([[  9.52845756e-01,  -1.43108591e-02,   2.11117645e-03, ...,
          -1.56719318e-05,  -6.18745455e-06,  -2.10164659e-06],
        [ -1.84650502e+00,   3.15029280e-02,  -4.30369641e-03, ...,
           2.93135685e-05,   1.31419916e-05,  -1.60626049e-06],
        [  9.52845756e-01,  -1.43108591e-02,   2.11117645e-03, ...,
          -1.56719318e-05,  -6.18745455e-06,  -2.10164659e-06],
        ..., 
        [  9.34781867e-01,  -1.42427070e-02,   2.09625005e-03, ...,
          -1.56964036e-05,  -6.17025148e-06,  -1.96098302e-06],
        [  4.02398043e-01,  -6.80205888e-03,   1.26562152e-03, ...,
          -1.04890778e-05,  -3.49163189e-06,  -7.88898674e-07],
        [  9.52845756e-01,  -1.43108591e-02,   2.11117645e-03, ...,
          -1.56719318e-05,  -6.18745455e-06,  -2.10164659e-06]])

In [14]:
result=(Y_new * np.linalg.inv(np.asmatrix(T)))

In [15]:
result

matrix([[  8.68084330e+16,  -1.14942377e-01,  -8.34452689e+16, ...,
          -4.26324394e-02,  -1.34676609e-01,   4.49549532e-01],
        [ -1.67678333e+17,   2.21743431e-01,   1.61173392e+17, ...,
           8.23947958e-02,   2.59647391e-01,  -8.66473950e-01],
        [  8.68084330e+16,  -1.14942377e-01,  -8.34452689e+16, ...,
          -4.26324394e-02,  -1.34676609e-01,   4.49549532e-01],
        ..., 
        [  8.51363048e+16,  -1.12709478e-01,  -8.18374135e+16, ...,
          -4.18096215e-02,  -1.32028853e-01,   4.40823451e-01],
        [  3.66496376e+16,  -4.84555429e-02,  -3.52338997e+16, ...,
          -1.81210695e-02,  -5.62986165e-02,   1.88934069e-01],
        [  8.68084330e+16,  -1.14942377e-01,  -8.34452689e+16, ...,
          -4.26324394e-02,  -1.34676609e-01,   4.49549532e-01]])

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
mean_squared_error(Y_scaled, result)

4.9379258661902941e+33

In [18]:
mean_squared_error(Y_train, result)

4.9379258661902941e+33

In [19]:
crimes = ['Assault', 'Break and Enter', 'Homicide', 'Robbery', 'Sexual Assaults',
       'Theft From Vehicle', 'Theft Of Vehicle', 'Theft Over $5000']

In [20]:
result1 = []
for i in range(len(crimes)):
    result1.append([np.sqrt(mean_squared_error(Y_train[crimes[i]], result[:,i])), crimes[i], 'Linear Regression'])
    
result1

[[1.4323912137542741e+17, 'Assault', 'Linear Regression'],
 [1.8412069850297326, 'Break and Enter', 'Linear Regression'],
 [1.3767725090280502e+17, 'Homicide', 'Linear Regression'],
 [5561979950019495.0, 'Robbery', 'Linear Regression'],
 [0.50066098643708534, 'Sexual Assaults', 'Linear Regression'],
 [2.9039072147423308, 'Theft From Vehicle', 'Linear Regression'],
 [1.5141719735537931, 'Theft Of Vehicle', 'Linear Regression'],
 [0.82954015935895908, 'Theft Over $5000', 'Linear Regression']]

In [21]:
final = []
for i in result1:
    final.append(i[0])
final

[1.4323912137542741e+17,
 1.8412069850297326,
 1.3767725090280502e+17,
 5561979950019495.0,
 0.50066098643708534,
 2.9039072147423308,
 1.5141719735537931,
 0.82954015935895908]

In [22]:
b = [[1510338621318495.0, 'Assault', 'Linear Regression'],
 [1.8067644105870351, 'Break and Enter', 'Linear Regression'],
 [3488399634215690.5, 'Homicide', 'Linear Regression'],
 [1978123031011947.2, 'Robbery', 'Linear Regression'],
 [0.49693393076651105, 'Sexual Assaults', 'Linear Regression'],
 [2.8372757248429941, 'Theft From Vehicle', 'Linear Regression'],
 [1.4609922366816115, 'Theft Of Vehicle', 'Linear Regression'],
 [0.33590054444014728, 'Theft Over $5000', 'Linear Regression']]

In [23]:
[x[0] for x in b]

[1510338621318495.0,
 1.806764410587035,
 3488399634215690.5,
 1978123031011947.2,
 0.49693393076651105,
 2.837275724842994,
 1.4609922366816115,
 0.3359005444401473]