In [1]:
from sklearn import preprocessing

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
pf = pd.read_csv("test1.csv")
X = pf.ix[:,0:3]
Y = pf.ix[:,3:5]

In [5]:
X_scaled = preprocessing.scale(X)
Y_scaled = preprocessing.scale(Y)

In [6]:
X_scaled.mean(axis=0)

array([  1.77635684e-17,  -3.19744231e-16,  -3.33066907e-18])

In [7]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.])

In [8]:
from sklearn.cross_decomposition import CCA
n_components=2
cca = CCA(n_components)
cca.fit(X_scaled,Y_scaled)
X_c, Y_c = cca.transform(X_scaled, Y_scaled)

c = []
for i in range(n_components):
    c.append(np.corrcoef(X_c[:,i], Y_c[:,i])[0,1])

print(c)
    
T = np.empty(shape=(n_components,n_components))
for i in range(n_components):
     T[i] = Y_c.T[:,i]
        
print(T)

[0.99999726146386514, 0.9348427972813862]
[[ 0.48496522 -0.85929838]
 [-1.28609895  0.38087683]]


In [9]:
# import rcca
# cca = rcca.CCA(kernelcca = False, reg = 0, numCC = 2)
# cca.train([X_scaled,Y_scaled])
# c = cca.cancorrs
# T1 = cca.validate([X_scaled,Y_scaled])
# T = np.empty(shape=(2,2))
# T[0] = T1[0][0:2]
# T[1] = T1[1]
# T

In [10]:
from sklearn import linear_model

In [11]:
regr = linear_model.LinearRegression()
Y_star = Y_scaled * np.asmatrix(T)
Y_hat = np.empty(shape=(len(X_scaled),2))

for x in range(2):
    regr.fit(X_scaled, Y_star[:,x])
    Y_hat[:, x] = np.ndarray.flatten(regr.predict(X_scaled))

In [12]:
Y_hat

array([[ -9.89848889e-01,   8.22615806e-01],
       [  1.84451734e+00,  -8.22873739e-01],
       [  7.60719507e-01,   3.37818621e-01],
       [  2.28484164e+00,  -1.04905686e+00],
       [ -4.64780068e-01,   1.21796259e+00],
       [ -7.12129477e-01,   5.55509553e-01],
       [  7.58723482e-01,  -7.06104773e-01],
       [  1.28345828e+00,  -5.13955016e-01],
       [ -4.97920918e-01,  -4.02693830e-01],
       [ -2.24266821e+00,   1.27357541e+00],
       [  2.30014190e+00,  -1.14281191e+00],
       [  1.64512685e+00,  -1.16481300e+00],
       [  6.35954510e-01,  -1.20182113e+00],
       [ -4.71297581e-01,  -7.13113008e-01],
       [  1.54520318e+00,  -1.17578280e+00],
       [  3.46069821e-01,   1.23703058e+00],
       [  1.52136572e+00,  -3.37479694e-01],
       [ -5.86174943e-01,  -1.10648145e+00],
       [  4.90304103e-01,   8.46810933e-01],
       [  4.02476454e-01,   1.22905511e+00],
       [  1.12354865e+00,   4.30763407e-01],
       [ -1.22830939e+00,   7.49996789e-01],
       [  

In [13]:
r = len(X_scaled.T)/len(X_scaled)
dx=[]
for i in range(len(c)):
    dxi=((1-r)*(c[i]**2-r))/((1-r)**2)*c[i]**2+(r**2)*(1-c[i]**2)
    if dxi<0:
        dx.append(0)
    else:
        dx.append(dxi)

In [14]:
dx = np.asmatrix(dx)
Y_new = np.multiply(Y_hat, dx)
Y_new

matrix([[ -9.89837965e-01,   6.26920487e-01],
        [  1.84449698e+00,  -6.27117059e-01],
        [  7.60711112e-01,   2.57453616e-01],
        [  2.28481642e+00,  -7.99492587e-01],
        [ -4.64774939e-01,   9.28216666e-01],
        [ -7.12121618e-01,   4.23357194e-01],
        [  7.58715109e-01,  -5.38126723e-01],
        [  1.28344411e+00,  -3.91688230e-01],
        [ -4.97915423e-01,  -3.06895406e-01],
        [ -2.24264346e+00,   9.70599533e-01],
        [  2.30011651e+00,  -8.70943875e-01],
        [  1.64510870e+00,  -8.87711039e-01],
        [  6.35947492e-01,  -9.15915161e-01],
        [ -4.71292380e-01,  -5.43467741e-01],
        [  1.54518613e+00,  -8.96071194e-01],
        [  3.46066002e-01,   9.42748494e-01],
        [  1.52134893e+00,  -2.57195318e-01],
        [ -5.86168474e-01,  -8.43256209e-01],
        [  4.90298692e-01,   6.45359739e-01],
        [  4.02472012e-01,   9.36670338e-01],
        [  1.12353625e+00,   3.28287401e-01],
        [ -1.22829584e+00,   5.715

In [15]:
result=(Y_new * np.linalg.inv(np.asmatrix(T)))

In [16]:
result

matrix([[-0.46638538,  0.59377801],
        [ 0.11299973, -1.39156947],
        [-0.67451906, -0.84583647],
        [ 0.17165109, -1.71182133],
        [-1.10465291, -0.05516162],
        [-0.29687038,  0.44176213],
        [ 0.43795497, -0.42479016],
        [ 0.01620512, -0.99182508],
        [ 0.63485746,  0.62654527],
        [-0.4281866 ,  1.58229493],
        [ 0.26515729, -1.6884583 ],
        [ 0.55962978, -1.06811977],
        [ 1.01663258, -0.11112368],
        [ 0.95439843,  0.72633791],
        [ 0.6126595 , -0.97042889],
        [-1.4604862 , -0.81980552],
        [-0.27016474, -1.28479184],
        [ 1.42082276,  0.99153965],
        [-1.1046349 , -0.7977677 ],
        [-1.47533428, -0.86926269],
        [-0.92363172, -1.22188538],
        [-0.29038065,  0.84555805],
        [-0.19707797, -1.38500429],
        [-0.42964388,  1.24250705],
        [ 1.41362082,  0.5846741 ],
        [-0.07303322, -1.20171469],
        [ 1.23489493,  0.90048819],
        [ 1.04638335,  1.419

In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
mean_squared_error(Y_scaled, result)

0.087559035986231895

In [ ]:
o