In [1]:
# Author: Baihong Qi
# for CMPUT 466 course project
# License: MIT
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 100)

In [2]:
table = pd.read_csv('ll.csv')
print(table)

      LATITUDE   LONGITUDE
0    53.574607 -113.393664
1    53.469872 -113.362193
2    53.521497 -113.491246
3    53.526131 -113.607490
4    53.500922 -113.523411
5    53.519264 -113.636948
6    53.501205 -113.504390
7    53.568831 -113.521355
8    53.539950 -113.434528
9    53.588071 -113.544272
10   53.491482 -113.524603
11   53.512255 -113.449284
12   53.592245 -113.450625
13   53.604793 -113.377835
14   53.633422 -113.506254
15   53.575100 -113.411476
16   53.510351 -113.531450
17   53.525109 -113.638686
18   53.592848 -113.393152
19   53.594809 -113.436662
20   53.487097 -113.671717
21   53.460383 -113.398001
22   53.530954 -113.431457
23   53.493484 -113.577079
24   53.549499 -113.587284
25   53.546426 -113.597780
26   53.493226 -113.566790
27   53.610415 -113.525853
28   53.589312 -113.525135
29   53.509121 -113.622965
30   53.492940 -113.623530
31   53.555050 -113.496280
32   53.543008 -113.497591
33   53.532615 -113.435817
34   53.555286 -113.561347
35   53.440310 -113.405993
3

In [3]:
LAT = table.ix[:,0]
print(LAT)

0      53.574607
1      53.469872
2      53.521497
3      53.526131
4      53.500922
5      53.519264
6      53.501205
7      53.568831
8      53.539950
9      53.588071
10     53.491482
11     53.512255
12     53.592245
13     53.604793
14     53.633422
15     53.575100
16     53.510351
17     53.525109
18     53.592848
19     53.594809
20     53.487097
21     53.460383
22     53.530954
23     53.493484
24     53.549499
25     53.546426
26     53.493226
27     53.610415
28     53.589312
29     53.509121
30     53.492940
31     53.555050
32     53.543008
33     53.532615
34     53.555286
35     53.440310
36     53.533307
37     53.450099
38     53.445611
39     53.575560
40     53.596816
41     53.605253
42     53.514231
43     53.573317
44     53.623668
45     53.475981
46     53.471215
47     53.622764
48     53.474298
49     53.568293
         ...    
159    53.447271
160    53.578152
161    53.589176
162    53.513316
163    53.592070
164    53.476999
165    53.478793
166    53.5095

In [4]:
LON = table.ix[:,1]
print(LON)

0     -113.393664
1     -113.362193
2     -113.491246
3     -113.607490
4     -113.523411
5     -113.636948
6     -113.504390
7     -113.521355
8     -113.434528
9     -113.544272
10    -113.524603
11    -113.449284
12    -113.450625
13    -113.377835
14    -113.506254
15    -113.411476
16    -113.531450
17    -113.638686
18    -113.393152
19    -113.436662
20    -113.671717
21    -113.398001
22    -113.431457
23    -113.577079
24    -113.587284
25    -113.597780
26    -113.566790
27    -113.525853
28    -113.525135
29    -113.622965
30    -113.623530
31    -113.496280
32    -113.497591
33    -113.435817
34    -113.561347
35    -113.405993
36    -113.570846
37    -113.399042
38    -113.453499
39    -113.477991
40    -113.454160
41    -113.476542
42    -113.461319
43    -113.561336
44    -113.422012
45    -113.505057
46    -113.505964
47    -113.526828
48    -113.581777
49    -113.445155
          ...    
159   -113.413143
160   -113.541181
161   -113.459179
162   -113.503601
163   -113

In [5]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(table)
kmeans.labels_

array([2, 0, 0, 1, 1, 1, 0, 2, 2, 1, 1, 0, 2, 2, 2, 2, 1, 1, 2, 2, 1, 0, 0,
       1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 0, 1, 0, 1, 0, 0, 2, 2, 2, 0, 1, 2, 0,
       0, 2, 1, 2, 0, 1, 2, 1, 0, 1, 0, 1, 1, 2, 2, 2, 2, 1, 1, 0, 1, 2, 1,
       2, 0, 1, 1, 0, 1, 2, 0, 0, 2, 1, 0, 0, 2, 2, 1, 0, 2, 1, 1, 2, 2, 2,
       0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 1, 1, 2, 1, 2, 0, 2, 2, 2, 0,
       1, 0, 1, 1, 2, 2, 0, 1, 1, 2, 0, 1, 2, 1, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 1, 1, 0, 2, 1, 1, 1, 0, 1,
       2, 0, 2, 1, 0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1, 2, 1, 2, 2, 2, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 2, 0, 1, 2, 0, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       2, 1], dtype=int32)

In [6]:
kmeans.labels_

array([2, 0, 0, 1, 1, 1, 0, 2, 2, 1, 1, 0, 2, 2, 2, 2, 1, 1, 2, 2, 1, 0, 0,
       1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 0, 1, 0, 1, 0, 0, 2, 2, 2, 0, 1, 2, 0,
       0, 2, 1, 2, 0, 1, 2, 1, 0, 1, 0, 1, 1, 2, 2, 2, 2, 1, 1, 0, 1, 2, 1,
       2, 0, 1, 1, 0, 1, 2, 0, 0, 2, 1, 0, 0, 2, 2, 1, 0, 2, 1, 1, 2, 2, 2,
       0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 1, 1, 2, 1, 2, 0, 2, 2, 2, 0,
       1, 0, 1, 1, 2, 2, 0, 1, 1, 2, 0, 1, 2, 1, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 1, 1, 0, 2, 1, 1, 1, 0, 1,
       2, 0, 2, 1, 0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1, 2, 1, 2, 2, 2, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 2, 0, 1, 2, 0, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       2, 1], dtype=int32)

In [7]:
kmeans.cluster_centers_

array([[  53.47982618, -113.45712129],
       [  53.52069229, -113.57755229],
       [  53.58899601, -113.45676457]])